### ISSUE TITLE
Issue: File attachment

### ISSUE THREAD

**Issue by inflameous48** [ezl/dailyidea.com#407]
There's an issue with the Attach Files function when posting an idea. When attaching the file you are no longer allowed to post the idea. Here's a video showcasing the issue: https://www.loom.com/share/44a16c2be7e94e82ac7f135baaf2d1e8

This has been replicated with 2 different images and a txt file.

Attached is a log file of the console output when attaching the file.

`4120da952a744e956194.js:2 Uncaught (in promise) MissingRequiredParameter: Missing required key 'Bucket' in params
    at constructor.fail (https://dailyidea-serverless-prod.s3.amazonaws.com/client/4120da952a744e956194.js:2:1293792)
    at constructor.validateStructure (https://dailyidea-serverless-prod.s3.amazonaws.com/client/4120da952a744e956194.js:2:1293994)
    at constructor.validateMember (https://dailyidea-serverless-prod.s3.amazonaws.com/client/4120da952a744e956194.js:2:1294374)
    at constructor.validate (https://dailyidea-serverless-prod.s3.amazonaws.com/client/4120da952a744e956194.js:2:1293445)
    at constructor.<anonymous> (https://dailyidea-serverless-prod.s3.amazonaws.com/client/4120da952a744e956194.js:2:1258303)
    at constructor.callListeners (https://dailyidea-serverless-prod.s3.amazonaws.com/client/4120da952a744e956194.js:2:436163)
    at f (https://dailyidea-serverless-prod.s3.amazonaws.com/client/4120da952a744e956194.js:2:436049)
    at https://dailyidea-serverless-prod.s3.amazonaws.com/client/4120da952a744e956194.js:2:1257629
    at r (https://dailyidea-serverless-prod.s3.amazonaws.com/client/4120da952a744e956194.js:2:1254713)
    at constructor.getCredentials (https://dailyidea-serverless-prod.s3.amazonaws.com/client/4120da952a744e956194.js:2:1255116)
    at constructor.<anonymous> (https://dailyidea-serverless-prod.s3.amazonaws.com/client/4120da952a744e956194.js:2:1257497)
    at constructor.callListeners (https://dailyidea-serverless-prod.s3.amazonaws.com/client/4120da952a744e956194.js:2:436134)
    at constructor.emit (https://dailyidea-serverless-prod.s3.amazonaws.com/client/4120da952a744e956194.js:2:435873)
    at constructor.emitEvent (https://dailyidea-serverless-prod.s3.amazonaws.com/client/4120da952a744e956194.js:2:1277172)
    at constructor.t (https://dailyidea-serverless-prod.s3.amazonaws.com/client/4120da952a744e956194.js:2:1272714)
    at n.runTo (https://dailyidea-serverless-prod.s3.amazonaws.com/client/4120da952a744e956194.js:2:1279033)
    at constructor.runTo (https://dailyidea-serverless-prod.s3.amazonaws.com/client/4120da952a744e956194.js:2:1274439)
    at constructor.send (https://dailyidea-serverless-prod.s3.amazonaws.com/client/4120da952a744e956194.js:2:1274332)
    at constructor.nextChunk (https://dailyidea-serverless-prod.s3.amazonaws.com/client/4120da952a744e956194.js:2:1372259)
    at constructor.fillBuffer (https://dailyidea-serverless-prod.s3.amazonaws.com/client/4120da952a744e956194.js:2:1371105)
    at constructor.send (https://dailyidea-serverless-prod.s3.amazonaws.com/client/4120da952a744e956194.js:2:1369480)
    at https://dailyidea-serverless-prod.s3.amazonaws.com/client/4120da952a744e956194.js:2:75474
    at new Promise (<anonymous>)
    at constructor.promise (https://dailyidea-serverless-prod.s3.amazonaws.com/client/4120da952a744e956194.js:2:75405)
    at t.<anonymous> (https://dailyidea-serverless-prod.s3.amazonaws.com/client/4120da952a744e956194.js:2:423867)
    at https://dailyidea-serverless-prod.s3.amazonaws.com/client/4120da952a744e956194.js:2:420747
    at Object.next (https://dailyidea-serverless-prod.s3.amazonaws.com/client/4120da952a744e956194.js:2:420852)
    at l (https://dailyidea-serverless-prod.s3.amazonaws.com/client/4120da952a744e956194.js:2:419589)`

**Comment by vedmant** [comment]
@inflameous48 I couldn't reproduce this on dev branch, tried jpg and txt files. Could you attach here specific file you are getting error with? 

The only issue I found it wrong redirect url after creating post, I'll add separate issue for this.

**Comment by inflameous48** [comment]
@vedmant this appears to be working now. In the past, it seems like it was stuck on the loading bar and it never fully uploaded.
